{% set name = "eodms-api-client" %}
{% set version = "1.2.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/m9brady/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 92700dcd0a6d7eb26aad7bd22b6c53160f0dd7568eb50d7b6f5bd23fa4d9bc98

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - eodms = eodms_api_client.cli:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - click
    - python-dateutil
    - tqdm
    - pandas >=1.0.0
    - geopandas >=0.8
    - pyproj
    - fiona

test:
  imports:
    - eodms_api_client
  commands:
    - eodms -h

about:
  home: https://github.com/m9brady/eodms-api-client
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'REST API client package for EODMS'
  description: |
    A Python3 package for querying, ordering and downloading from the REST API
    provided by Natural Resources Canada's Earth Observation Data Management
    System (EODMS).
  doc_url: https://eodms-api-client.readthedocs.io/en/latest/
  dev_url: https://github.com/m9brady/eodms-api-client

extra:
  recipe-maintainers:
    - m9brady
