{% set name = "eodms-api-client" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/m9brady/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d08689758ecfe325f2a6963c52cf5f56cf101f372ca591d3f0d07ec694341d8a

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - eodms = eodms_api_client.cli:cli

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests
    - click
    - python-dateutil
    - tqdm
    - pandas >=1.0.0
    - geopandas >=0.8
    - pyproj
    - fiona

test:
  requires:
    - python {{ python_min }}
  imports:
    - eodms_api_client
  commands:
    - eodms -h

about:
  home: https://github.com/m9brady/eodms-api-client
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'REST API client package for EODMS'
  description: |
    A Python3 package for querying, ordering and downloading from the REST API
    provided by Natural Resources Canada's Earth Observation Data Management
    System (EODMS).
  doc_url: https://eodms-api-client.readthedocs.io/en/latest/
  dev_url: https://github.com/m9brady/eodms-api-client

extra:
  recipe-maintainers:
    - m9brady
